"""Constants for Media_Tracker component."""
DOMAIN = "media_tracker"

CONF_NAME = "name"
CONF_SSL = "ssl"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_TOKEN = "token"
CONF_DAYS = "days"
CONF_JSON_ONLY = "json_only"
